//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contratacao()
        {
            this.HorasExtras = new HashSet<HEContratacao>();
            this.ContratacaoMeses = new HashSet<ContratacaoMes>();
            this.CalculosEventosContratacoes = new HashSet<CalculoEventoContratacao>();
        }
    
        public int Codigo { get; set; }
        public double Insalubridade { get; set; }
        public string Motivo { get; set; }
        public bool Periculosidade { get; set; }
        public string CentroCustoCod { get; set; }
        public int CargaHoraria { get; set; }
        public int EmpresaCod { get; set; }
        public string CidadeNome { get; set; }
        public Nullable<int> CargoCod { get; set; }
        public int CicloCod { get; set; }
        public Nullable<int> ConvenioPlanoCod { get; set; }
        public float Salario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HEContratacao> HorasExtras { get; set; }
        public virtual CentroCusto CentroCusto { get; set; }
        public virtual Ciclo Ciclo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratacaoMes> ContratacaoMeses { get; set; }
        public virtual ConvenioMed ConvenioMed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalculoEventoContratacao> CalculosEventosContratacoes { get; set; }
        public virtual Filial Filial { get; set; }
        public virtual Variaveis Variaveis { get; set; }
    }
}
