//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrcamentoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutrosBase
    {
        public string FuncionarioMatricula { get; set; }
        public System.DateTime Mes { get; set; }
        public double Outros { get; set; }
        public double RemProdutividade { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
